import {
  LitElement,
  css,
  html,
  nothing,
  customElement,
  property,
  state,
} from "@umbraco-cms/backoffice/external/lit";
import { reframeShared } from "./reframe.styles.js";
import type { ReframeModeName, ReframeRatioOption } from "./reframe.repository.js";

/**
 * Presentational controls rail: ratio chips drawn as scaled rectangles, a custom x:y input, and the
 * Crop/Outpaint mode toggle with honest trade-off hints. Emits events; holds no reframe state of its
 * own beyond the custom-ratio inputs.
 */
@customElement("reframe-controls-rail")
export class ReframeControlsRailElement extends LitElement {
  @property({ attribute: false }) presets: ReframeRatioOption[] = [];
  @property({ type: String }) sourceRatio = "";
  @property({ type: String }) selectedRatio?: string;
  @property({ type: String }) selectedMode: ReframeModeName = "outpaint";
  @property({ type: String }) providerName = "";
  @property({ type: Boolean }) disabled = false;

  @state() private _customX = 16;
  @state() private _customY = 9;

  private get _selectedOption() {
    return this.presets.find((p) => p.ratio === this.selectedRatio);
  }

  private get _cropAllowed() {
    // Advisory flag from the server for presets; custom ratios fall back to allowed.
    return this._selectedOption?.canCrop ?? true;
  }

  #emitRatio(ratio: string) {
    this.dispatchEvent(new CustomEvent("ratio-change", { detail: ratio }));
  }

  #emitMode(mode: ReframeModeName) {
    this.dispatchEvent(new CustomEvent("mode-change", { detail: mode }));
  }

  #applyCustom() {
    if (this._customX > 0 && this._customY > 0) {
      this.#emitRatio(`${this._customX}:${this._customY}`);
    }
  }

  render() {
    return html`
      <div class="rf-rail">
        <section>
          <header class="rf-section-head">
            <span>Aspect ratio</span>
            ${this.sourceRatio ? html`<span class="rf-meta">Current ${this.sourceRatio}</span>` : nothing}
          </header>
          <div class="rf-chips">
            ${this.presets.map((p) => this.#renderChip(p))}
          </div>
          <div class="rf-custom">
            <span class="rf-meta">Custom</span>
            <div class="rf-custom-row">
              <uui-input
                type="number"
                .value=${String(this._customX)}
                ?disabled=${this.disabled}
                @change=${(e: Event) => (this._customX = Number((e.target as HTMLInputElement).value))}
              ></uui-input>
              <span>:</span>
              <uui-input
                type="number"
                .value=${String(this._customY)}
                ?disabled=${this.disabled}
                @change=${(e: Event) => (this._customY = Number((e.target as HTMLInputElement).value))}
              ></uui-input>
              <uui-button
                look="secondary"
                compact
                label="Apply custom ratio"
                ?disabled=${this.disabled}
                @click=${this.#applyCustom}
                >Apply</uui-button
              >
            </div>
          </div>
        </section>

        <section>
          <header class="rf-section-head"><span>Mode</span></header>
          <div class="rf-modes">
            <button
              class="rf-mode ${this.selectedMode === "crop" ? "rf-mode--active" : ""}"
              ?disabled=${this.disabled || !this._cropAllowed}
              @click=${() => this.#emitMode("crop")}
            >
              <uui-icon name="icon-crop"></uui-icon>
              <span class="rf-mode-title">Crop</span>
              <span class="rf-meta">Instant · free</span>
            </button>
            <button
              class="rf-mode ${this.selectedMode === "outpaint" ? "rf-mode--active" : ""}"
              ?disabled=${this.disabled}
              @click=${() => this.#emitMode("outpaint")}
            >
              <uui-icon name="icon-wand"></uui-icon>
              <span class="rf-mode-title">Outpaint</span>
              <span class="rf-meta">AI · slower</span>
            </button>
          </div>
          ${!this._cropAllowed && this.selectedRatio
            ? html`<p class="rf-hint">This ratio can't be reached by cropping without losing most of the image — outpaint will extend it instead.</p>`
            : nothing}
          ${this.selectedMode === "outpaint" && this.providerName
            ? html`<p class="rf-hint">New pixels are generated by <strong>${this.providerName}</strong>.</p>`
            : nothing}
        </section>
      </div>
    `;
  }

  #renderChip(p: ReframeRatioOption) {
    const [w, h] = p.ratio.split(":").map(Number);
    const maxEdge = 30;
    const scale = maxEdge / Math.max(w, h);
    const selected = p.ratio === this.selectedRatio;
    return html`
      <button
        class="rf-chip ${selected ? "rf-chip--selected" : ""}"
        ?disabled=${this.disabled}
        @click=${() => this.#emitRatio(p.ratio)}
        title=${p.canCrop ? `${p.ratio}` : `${p.ratio} — needs outpaint`}
      >
        <span class="rf-chip-rect" style=${`width:${w * scale}px;height:${h * scale}px`}></span>
        <span class="rf-chip-label">${p.ratio}</span>
        ${!p.canCrop ? html`<span class="rf-chip-ai" title="Needs outpaint">AI</span>` : nothing}
      </button>
    `;
  }

  static styles = [
    reframeShared,
    css`
      .rf-rail {
        display: flex;
        flex-direction: column;
        gap: var(--uui-size-layout-1, 24px);
        padding: var(--uui-size-space-5, 18px);
        width: 280px;
        box-sizing: border-box;
        border-right: 1px solid var(--uui-color-border, #e5e4df);
        overflow: auto;
      }

      .rf-section-head {
        display: flex;
        justify-content: space-between;
        align-items: baseline;
        font-weight: 700;
        margin-bottom: var(--uui-size-space-4, 12px);
      }

      .rf-meta {
        font-size: 11px;
        color: var(--uui-color-text-alt, #68686a);
        font-weight: 400;
      }

      .rf-chips {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 6px;
      }

      .rf-chip {
        position: relative;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 6px;
        min-height: 64px;
        padding: 8px;
        background: var(--uui-color-surface, #fff);
        border: 1px solid var(--uui-color-border, #e5e4df);
        border-radius: var(--uui-border-radius, 3px);
        cursor: pointer;
        color: inherit;
      }

      .rf-chip:hover:not(:disabled) {
        border-color: var(--uui-color-border-emphasis, #a1a1a1);
      }

      .rf-chip--selected {
        border-color: var(--uui-color-selected, #3544b1);
        box-shadow: inset 0 0 0 1px var(--uui-color-selected, #3544b1);
      }

      .rf-chip:disabled {
        opacity: 0.5;
        cursor: default;
      }

      .rf-chip-rect {
        background: var(--uui-color-text-alt, #68686a);
        border-radius: 1px;
      }

      .rf-chip-label {
        font-size: 11px;
        font-variant-numeric: tabular-nums;
      }

      .rf-chip-ai {
        position: absolute;
        top: 4px;
        right: 4px;
        font-size: 8px;
        font-weight: 700;
        letter-spacing: 0.04em;
        background: var(--rf-ai);
        color: #fff;
        padding: 1px 4px;
        border-radius: 999px;
      }

      .rf-custom {
        margin-top: var(--uui-size-space-4, 12px);
      }

      .rf-custom-row {
        display: flex;
        align-items: center;
        gap: 6px;
        margin-top: 6px;
      }

      .rf-custom-row uui-input {
        width: 56px;
      }

      .rf-modes {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 6px;
      }

      .rf-mode {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 4px;
        padding: 12px 8px;
        background: var(--uui-color-surface, #fff);
        border: 1px solid var(--uui-color-border, #e5e4df);
        border-radius: var(--uui-border-radius, 3px);
        cursor: pointer;
        color: inherit;
      }

      .rf-mode--active {
        border-color: var(--uui-color-selected, #3544b1);
        box-shadow: inset 0 0 0 1px var(--uui-color-selected, #3544b1);
      }

      .rf-mode:disabled {
        opacity: 0.5;
        cursor: default;
      }

      .rf-mode-title {
        font-weight: 700;
        font-size: 13px;
      }

      .rf-hint {
        margin: var(--uui-size-space-3, 9px) 0 0;
        font-size: 11px;
        color: var(--uui-color-text-alt, #68686a);
      }
    `,
  ];
}

export default ReframeControlsRailElement;

declare global {
  interface HTMLElementTagNameMap {
    "reframe-controls-rail": ReframeControlsRailElement;
  }
}
